#!/bin/sh

mkdir -p ~/downloads ~/tars

yuminstalls="git npm wget vim"
yum install -y $yuminstalls
yum group install -y "Development Tools"

curl https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

. ~/.bashrc

nvm install 0.11.16
nvm alias default 0.11.16

. ~/.bashrc

npm install -g lodash mocha grunt grunt-cli grunt-init selenium-webdriver@latest chromedriver@latest
